"""
Q-SENTINEL Append-Only Evidence Ledger.

Tamper-evident SQLite-backed ledger.
Uses HMAC-SHA256 to prevent an adversary with DB write access from forging the chain.
Uses BEGIN IMMEDIATE for atomicity to prevent race conditions.
"""
import sqlite3
import hmac
import hashlib
import json
import os
import time

# In a real system, this key would be in an HSM.
# For Track A, it's injected via env var.
LEDGER_SECRET = os.environ.get("QSENTINEL_LEDGER_SECRET", "default_insecure_secret_for_demo").encode('utf-8')

class EvidenceLedger:
    
    def __init__(self, db_path=None):
        self.db_path = db_path or os.environ.get("QSENTINEL_DB_PATH", "data/ledger.db")
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self._init_db()

    def _init_db(self):
        # We don't hold a long-lived connection to avoid threading issues
        # and enforce transaction boundaries properly.
        with sqlite3.connect(self.db_path) as conn:
            conn.execute('''
                CREATE TABLE IF NOT EXISTS evidence (
                    seq_num INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_id TEXT UNIQUE NOT NULL,
                    timestamp REAL NOT NULL,
                    session_id TEXT NOT NULL,
                    signer_id TEXT NOT NULL,
                    verifier_id TEXT NOT NULL,
                    decision TEXT NOT NULL,
                    findings TEXT NOT NULL,
                    experiment_id TEXT,
                    previous_hash TEXT NOT NULL,
                    current_hash TEXT NOT NULL,
                    signature TEXT NOT NULL
                )
            ''')
            
            # Create genesis block if table is empty
            cursor = conn.cursor()
            cursor.execute("SELECT COUNT(*) FROM evidence")
            if cursor.fetchone()[0] == 0:
                self._insert_genesis(conn)
                
            conn.commit()

    def _insert_genesis(self, conn: sqlite3.Connection):
        """Insert the genesis block."""
        genesis_hash = "0" * 64
        genesis_sig = hmac.new(LEDGER_SECRET, genesis_hash.encode(), hashlib.sha256).hexdigest()
        
        conn.execute('''
            INSERT INTO evidence (
                event_id, timestamp, session_id, signer_id, verifier_id, decision,
                findings, experiment_id, previous_hash, current_hash, signature
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            "genesis", 0.0, "genesis", "system", "system", "INFO",
            "[]", None, "0"*64, genesis_hash, genesis_sig
        ))

    def record_event(self, event_data: dict) -> str:
        """
        Record a verification event in the ledger.
        Uses BEGIN IMMEDIATE to prevent read-modify-write races.
        """
        event_id = event_data.get('event_id', f"evt-{time.time()}")
        
        for attempt in range(20):
            try:
                with sqlite3.connect(self.db_path, timeout=30.0, isolation_level=None) as conn:
                    conn.execute("BEGIN IMMEDIATE")
                    cursor = conn.cursor()
                    
                    # Read last hash strictly within the exclusive transaction
                    cursor.execute("SELECT seq_num, current_hash FROM evidence ORDER BY seq_num DESC LIMIT 1")
                    last_row = cursor.fetchone()
                    seq_num = last_row[0] + 1
                    previous_hash = last_row[1]
                    
                    canonical_fields = {
                        "seq_num": seq_num,
                        "event_id": event_id,
                        "timestamp": event_data.get('timestamp', time.time()),
                        "session_id": event_data['session_id'],
                        "signer_id": event_data['signer_id'],
                        "verifier_id": event_data['verifier_id'],
                        "decision": event_data['decision'],
                        "findings": event_data.get('findings', []),
                        "experiment_id": event_data.get('experiment_id')
                    }
                    
                    # Findings is a list of dicts, we serialize it to JSON for storage
                    findings_json = json.dumps(canonical_fields['findings'], sort_keys=True)
                    canonical_fields['findings'] = findings_json
                    
                    canonical_event = json.dumps(canonical_fields, sort_keys=True).encode('utf-8')
                    
                    # 1. Compute Hash over (prev_hash || canonical_event)
                    hash_input = previous_hash.encode('utf-8') + canonical_event
                    current_hash = hashlib.sha256(hash_input).hexdigest()
                    
                    # 2. Compute HMAC signature over current_hash to prove it was generated by the system
                    signature = hmac.new(LEDGER_SECRET, current_hash.encode('utf-8'), hashlib.sha256).hexdigest()
                    
                    cursor.execute('''
                        INSERT INTO evidence (
                            seq_num, event_id, timestamp, session_id, signer_id, verifier_id, decision,
                            findings, experiment_id, previous_hash, current_hash, signature
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    ''', (
                        canonical_fields['seq_num'], canonical_fields['event_id'], canonical_fields['timestamp'],
                        canonical_fields['session_id'], canonical_fields['signer_id'], canonical_fields['verifier_id'],
                        canonical_fields['decision'], canonical_fields['findings'], canonical_fields['experiment_id'],
                        previous_hash, current_hash, signature
                    ))
                    
                    conn.execute("COMMIT")
                    return event_id
            except (sqlite3.IntegrityError, sqlite3.OperationalError):
                if attempt == 19:
                    raise
                time.sleep(0.01 * (attempt + 1))

    def get_event(self, event_id: str) -> dict:
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            cursor.execute("SELECT * FROM evidence WHERE event_id=?", (event_id,))
            row = cursor.fetchone()
            if not row:
                return None
            result = dict(row)
            result['findings'] = json.loads(result['findings'])
            return result

    def create_checkpoint(self) -> dict:
        """Create an authenticated checkpoint for the current ledger state."""
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT seq_num, current_hash FROM evidence ORDER BY seq_num DESC LIMIT 1")
            row = cursor.fetchone()
            if not row:
                raise RuntimeError("Cannot checkpoint an empty ledger")
            seq_num, current_hash = row
            sig = hmac.new(
                LEDGER_SECRET,
                f"{seq_num}:{current_hash}".encode("utf-8"),
                hashlib.sha256
            ).hexdigest()
            return {
                "seq_num": seq_num,
                "current_hash": current_hash,
                "timestamp": time.time(),
                "signature": sig
            }

    def verify_checkpoint(self, checkpoint: dict) -> bool:
        """Verify that the ledger has not been rolled back or truncated relative to checkpoint."""
        expected_sig = hmac.new(
            LEDGER_SECRET,
            f"{checkpoint['seq_num']}:{checkpoint['current_hash']}".encode("utf-8"),
            hashlib.sha256
        ).hexdigest()
        if checkpoint.get("signature") != expected_sig:
            return False

        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT current_hash FROM evidence WHERE seq_num = ?", (checkpoint["seq_num"],))
            row = cursor.fetchone()
            if not row or row[0] != checkpoint["current_hash"]:
                return False

            cursor.execute("SELECT MAX(seq_num) FROM evidence")
            max_seq = cursor.fetchone()[0]
            if max_seq is None or max_seq < checkpoint["seq_num"]:
                return False
        return True

# Global instance
global_ledger = EvidenceLedger()
